"""rename_token_ciphertext_to_plaintext

Revision ID: d80e05bd3b26
Revises: 0004_sprint3_browser_pool
Create Date: 2026-04-14 21:01:36.708858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision: str = 'd80e05bd3b26'
down_revision: Union[str, None] = '0004_sprint3_browser_pool'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _table_exists(name: str) -> bool:
    return name in inspect(op.get_bind()).get_table_names()


def _drop_fk(table_name: str, fk_id: int) -> None:
    """Drop a foreign key by its ID using raw SQL (SQLite)."""
    op.execute(f"PRAGMA foreign_key_delete('{table_name}', {fk_id})")


def _get_fk_ids(table_name: str) -> list[int]:
    """Get all foreign key IDs for a table."""
    inspector = inspect(op.get_bind())
    try:
        return [fk['id'] for fk in inspector.get_foreign_keys(table_name)]
    except Exception:
        return []


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop tables only if they exist (idempotent for partial runs)
    if _table_exists('browser_profiles'):
        for idx_name in [op.f('ix_browser_profiles_region'), op.f('ix_browser_profiles_store_id')]:
            try:
                inspector = inspect(op.get_bind())
                indexes = inspector.get_indexes('browser_profiles')
                idx_short = idx_name.replace('ix_', '')
                if any(i['name'] in (idx_name, idx_short) for i in indexes):
                    op.drop_index(idx_name, table_name='browser_profiles')
            except Exception:
                pass
        op.drop_table('browser_profiles')

    if _table_exists('proxy_pool'):
        try:
            inspector = inspect(op.get_bind())
            indexes = inspector.get_indexes('proxy_pool')
            idx_short = op.f('ix_proxy_pool_country').replace('ix_', '')
            if any(i['name'] in (op.f('ix_proxy_pool_country'), idx_short) for i in indexes):
                op.drop_index(op.f('ix_proxy_pool_country'), table_name='proxy_pool')
        except Exception:
            pass
        op.drop_table('proxy_pool')

    if _table_exists('browser_sessions'):
        try:
            inspector = inspect(op.get_bind())
            indexes = inspector.get_indexes('browser_sessions')
            idx_short = op.f('ix_browser_sessions_profile_id').replace('ix_', '')
            if any(i['name'] in (op.f('ix_browser_sessions_profile_id'), idx_short) for i in indexes):
                op.drop_index(op.f('ix_browser_sessions_profile_id'), table_name='browser_sessions')
        except Exception:
            pass
        op.drop_table('browser_sessions')

    # Drop foreign key constraints using raw SQL (SQLite doesn't support FK names)
    for table_name, fk_ids in {
        'category_mappings': _get_fk_ids('category_mappings'),
        'content_variants': _get_fk_ids('content_variants'),
        'decision_audit_logs': _get_fk_ids('decision_audit_logs'),
        'demand_signal_snapshots': _get_fk_ids('demand_signal_snapshots'),
        'feedback_records': _get_fk_ids('feedback_records'),
        'incidents': _get_fk_ids('incidents'),
        'opportunity_batches': _get_fk_ids('opportunity_batches'),
        'opportunity_items': _get_fk_ids('opportunity_items'),
        'preflight_checks': _get_fk_ids('preflight_checks'),
        'pricing_decisions': _get_fk_ids('pricing_decisions'),
        'procurement_drafts': _get_fk_ids('procurement_drafts'),
        'publish_results': _get_fk_ids('publish_results'),
        'publish_tasks': _get_fk_ids('publish_tasks'),
        'store_authorizations': _get_fk_ids('store_authorizations'),
        'store_health_status': _get_fk_ids('store_health_status'),
        'supply_candidates': _get_fk_ids('supply_candidates'),
        'training_archive_packages': _get_fk_ids('training_archive_packages'),
    }.items():
        for fk_id in fk_ids:
            _drop_fk(table_name, fk_id)

    # Remaining alterations use batch_alter_table (which handles column changes)
    with op.batch_alter_table('decision_audit_logs') as batch_op:
        batch_op.alter_column('store_id',
                           existing_type=sa.VARCHAR(length=64),
                           nullable=True)
        batch_op.alter_column('summary',
                           existing_type=sa.TEXT(),
                           nullable=False)
        batch_op.drop_index(op.f('ix_decision_audit_logs_created_at'))
        batch_op.create_index(op.f('ix_decision_audit_logs_entity_id'), ['entity_id'], unique=False)

    with op.batch_alter_table('incidents') as batch_op:
        batch_op.alter_column('store_id',
                           existing_type=sa.VARCHAR(length=64),
                           nullable=True)
        batch_op.alter_column('severity',
                           existing_type=sa.VARCHAR(length=32),
                           type_=sa.String(length=16),
                           existing_nullable=False)
        batch_op.drop_index(op.f('ix_incidents_status'))
        batch_op.create_index(op.f('ix_incidents_platform'), ['platform'], unique=False)

    with op.batch_alter_table('opportunity_batches') as batch_op:
        batch_op.drop_index(op.f('ix_opportunity_batches_status'))

    with op.batch_alter_table('opportunity_items') as batch_op:
        batch_op.drop_index(op.f('ix_opportunity_items_status'))

    with op.batch_alter_table('publish_tasks') as batch_op:
        batch_op.drop_index(op.f('ix_publish_tasks_status'))

    with op.batch_alter_table('store_authorizations') as batch_op:
        batch_op.add_column(sa.Column('access_token_plaintext', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('refresh_token_plaintext', sa.Text(), nullable=True))
        batch_op.drop_column('access_token_ciphertext')
        batch_op.drop_column('refresh_token_ciphertext')

    with op.batch_alter_table('store_health_status') as batch_op:
        batch_op.create_index(op.f('ix_store_health_status_platform'), ['platform'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store_health_status') as batch_op:
        batch_op.drop_index(op.f('ix_store_health_status_platform'))

    with op.batch_alter_table('store_authorizations') as batch_op:
        batch_op.add_column(sa.Column('refresh_token_ciphertext', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('access_token_ciphertext', sa.TEXT(), nullable=True))
        batch_op.drop_column('refresh_token_plaintext')
        batch_op.drop_column('access_token_plaintext')

    with op.batch_alter_table('publish_tasks') as batch_op:
        batch_op.create_index(op.f('ix_publish_tasks_status'), ['status'], unique=False)

    with op.batch_alter_table('opportunity_items') as batch_op:
        batch_op.create_index(op.f('ix_opportunity_items_status'), ['status'], unique=False)

    with op.batch_alter_table('opportunity_batches') as batch_op:
        batch_op.create_index(op.f('ix_opportunity_batches_status'), ['status'], unique=False)

    with op.batch_alter_table('incidents') as batch_op:
        batch_op.drop_index(op.f('ix_incidents_platform'))
        batch_op.create_index(op.f('ix_incidents_status'), ['status'], unique=False)
        batch_op.alter_column('severity',
                           existing_type=sa.String(length=16),
                           type_=sa.VARCHAR(length=32),
                           existing_nullable=False)
        batch_op.alter_column('store_id',
                           existing_type=sa.VARCHAR(length=64),
                           nullable=False)

    with op.batch_alter_table('decision_audit_logs') as batch_op:
        batch_op.drop_index(op.f('ix_decision_audit_logs_entity_id'))
        batch_op.create_index(op.f('ix_decision_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.alter_column('summary',
                           existing_type=sa.TEXT(),
                           nullable=True)
        batch_op.alter_column('store_id',
                           existing_type=sa.VARCHAR(length=64),
                           nullable=False)

    # Recreate foreign keys using raw SQL
    fk_defs = {
        'training_archive_packages': [('batch_id', 'opportunity_batches', 'id'), ('store_id', 'stores', 'id')],
        'supply_candidates': [('opportunity_item_id', 'opportunity_items', 'id')],
        'store_health_status': [('store_id', 'stores', 'id')],
        'store_authorizations': [('store_id', 'stores', 'id')],
        'publish_tasks': [('store_id', 'stores', 'id'), ('opportunity_item_id', 'opportunity_items', 'id')],
        'publish_results': [('publish_task_id', 'publish_tasks', 'id')],
        'procurement_drafts': [('opportunity_item_id', 'opportunity_items', 'id')],
        'pricing_decisions': [('opportunity_item_id', 'opportunity_items', 'id')],
        'preflight_checks': [('opportunity_item_id', 'opportunity_items', 'id')],
        'opportunity_items': [('store_id', 'stores', 'id'), ('batch_id', 'opportunity_batches', 'id')],
        'opportunity_batches': [('store_id', 'stores', 'id')],
        'incidents': [('store_id', 'stores', 'id')],
        'feedback_records': [('opportunity_item_id', 'opportunity_items', 'id')],
        'demand_signal_snapshots': [('opportunity_item_id', 'opportunity_items', 'id')],
        'decision_audit_logs': [('store_id', 'stores', 'id')],
        'content_variants': [('opportunity_item_id', 'opportunity_items', 'id')],
        'category_mappings': [('opportunity_item_id', 'opportunity_items', 'id')],
    }
    for table_name, fks in fk_defs.items():
        for col, ref_table, ref_col in fks:
            op.execute(
                f"ALTER TABLE {table_name} ADD CONSTRAINT "
                f"fk_{table_name}_{col} FOREIGN KEY ({col}) REFERENCES {ref_table}({ref_col})"
            )

    op.create_table('browser_sessions',
    sa.Column('id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('profile_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('task_type', sa.VARCHAR(length=32), nullable=False),
    sa.Column('task_id', sa.VARCHAR(length=64), nullable=True),
    sa.Column('status', sa.VARCHAR(length=32), server_default=sa.text("'created'"), nullable=False),
    sa.Column('pages_visited', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('bytes_transferred', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('error_count', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('started_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ended_at', sa.DATETIME(), nullable=True),
    sa.Column('duration_seconds', sa.INTEGER(), nullable=True),
    sa.Column('last_error', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['browser_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_browser_sessions_profile_id'), 'browser_sessions', ['profile_id'], unique=False)
    op.create_table('proxy_pool',
    sa.Column('id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('host', sa.VARCHAR(length=100), nullable=False),
    sa.Column('port', sa.INTEGER(), nullable=False),
    sa.Column('proxy_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), nullable=True),
    sa.Column('password', sa.VARCHAR(length=100), nullable=True),
    sa.Column('country', sa.VARCHAR(length=10), nullable=False),
    sa.Column('region', sa.VARCHAR(length=50), nullable=True),
    sa.Column('city', sa.VARCHAR(length=50), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text("'true'"), nullable=False),
    sa.Column('last_checked_at', sa.DATETIME(), nullable=True),
    sa.Column('health_score', sa.FLOAT(), server_default=sa.text("'1.0'"), nullable=False),
    sa.Column('success_count', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('failure_count', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('avg_response_time_ms', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('provider', sa.VARCHAR(length=50), nullable=True),
    sa.Column('expires_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proxy_pool_country'), 'proxy_pool', ['country'], unique=False)
    op.create_table('browser_profiles',
    sa.Column('id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('store_id', sa.VARCHAR(length=64), nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('region', sa.VARCHAR(length=50), nullable=False),
    sa.Column('platform', sa.VARCHAR(length=32), server_default=sa.text("'chromium'"), nullable=False),
    sa.Column('user_agent', sa.VARCHAR(length=500), nullable=False),
    sa.Column('viewport_width', sa.INTEGER(), server_default=sa.text("'1920'"), nullable=False),
    sa.Column('viewport_height', sa.INTEGER(), server_default=sa.text("'1080'"), nullable=False),
    sa.Column('timezone', sa.VARCHAR(length=50), nullable=False),
    sa.Column('language', sa.VARCHAR(length=20), nullable=False),
    sa.Column('locale', sa.VARCHAR(length=10), nullable=False),
    sa.Column('platform_os', sa.VARCHAR(length=50), server_default=sa.text("'Win32'"), nullable=False),
    sa.Column('cpu_cores', sa.INTEGER(), server_default=sa.text("'8'"), nullable=False),
    sa.Column('memory_gb', sa.INTEGER(), server_default=sa.text("'8'"), nullable=False),
    sa.Column('webgl_vendor', sa.VARCHAR(length=100), nullable=False),
    sa.Column('webgl_renderer', sa.VARCHAR(length=200), nullable=False),
    sa.Column('canvas_noise_seed', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('audio_noise_seed', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('do_not_track', sa.BOOLEAN(), server_default=sa.text("'false'"), nullable=False),
    sa.Column('webrtc_policy', sa.VARCHAR(length=32), server_default=sa.text("'default'"), nullable=False),
    sa.Column('proxy_host', sa.VARCHAR(length=100), nullable=True),
    sa.Column('proxy_port', sa.INTEGER(), nullable=True),
    sa.Column('proxy_username', sa.VARCHAR(length=100), nullable=True),
    sa.Column('proxy_password', sa.VARCHAR(length=100), nullable=True),
    sa.Column('proxy_type', sa.VARCHAR(length=20), server_default=sa.text("'http'"), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text("'true'"), nullable=False),
    sa.Column('is_locked', sa.BOOLEAN(), server_default=sa.text("'false'"), nullable=False),
    sa.Column('last_used_at', sa.DATETIME(), nullable=True),
    sa.Column('total_uses', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('tags', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_browser_profiles_store_id'), 'browser_profiles', ['store_id'], unique=False)
    op.create_index(op.f('ix_browser_profiles_region'), 'browser_profiles', ['region'], unique=False)
    # ### end Alembic commands ###
